### ISSUE TITLE
accessing developer option

### ISSUE THREAD

**Issue by backslashxx** [backslashxx/bindhosts#10]
https://github.com/user-attachments/assets/127a05e8-c091-4b6b-8151-80f995f6ac06

Available since https://github.com/backslashxx/bindhosts/commit/05c2f950c25cd8beab3ec0df17067c42b5b164c4

This will allow a user to override operation modes in an easier way.
Thanks to @KOWX712 for full implementation.

--
alternatively you can
```
su -c echo "mode=2" > /data/adb/bindhosts/mode_override.sh
```
to enable the mode that you want to force

**Comment by shifuru** [comment]
> 0vlw.mp4 
> Click status pane five times.
> 
> Available since [05c2f95](https://github.com/backslashxx/bindhosts/commit/05c2f950c25cd8beab3ec0df17067c42b5b164c4)
> 
> This will allow a user to override operation modes in an easier way. Thanks to @KOWX712 for full implementation.
> 
> -- alternatively you can
> 
> ```
> su -c echo "mode=2" > /data/adb/bindhosts/mode_override.sh
> ```
> 
> to enable the mode that you want to force

Thank you! I started to use bindhosts module just recently, not really familiar with it's operation

**Comment by backslashxx** [comment]
> Thank you! I started to use bindhosts module just recently, not really familiar with it's operation

Do not worry, I only also started adding these operation modes yesterday, its a really new feature.
https://github.com/backslashxx/bindhosts/commit/7152443ee950516242ce7e800541c81c4c94cfbe
