### ISSUE TITLE
bindhosts generating custom rules when certain ads list is loaded

### ISSUE THREAD

**Issue by dynux90** [backslashxx/bindhosts#17]
Hello,

using bindhosts 1.7.2

when loading a custom ads list: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts bindhosts generates 8 custom rules that are not visible in the WebUI Manager:

![image](https://github.com/user-attachments/assets/d28b6701-5e87-4e7d-9333-d7d605d9f355)
![image](https://github.com/user-attachments/assets/76935a14-cfe0-4d6e-bb2d-128c5971117b)

**Comment by backslashxx** [comment]
the issues is not on bindhosts side, this is on stevenblack's list
stevenblack's list adss some more ipv6 loopbacks
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
```
# Title: StevenBlack/hosts
#
# This hosts file is a merged collection of hosts from reputable sources,
# with a dash of crowd sourcing via GitHub
#
# Date: 28 November 2024 21:47:49 (UTC)
# Number of unique domains: 121,859
#
# Fetch the latest version of this file: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
# Project home page: https://github.com/StevenBlack/hosts
# Project releases: https://github.com/StevenBlack/hosts/releases
#
# ===============================================================

127.0.0.1 localhost
127.0.0.1 localhost.localdomain
127.0.0.1 local
255.255.255.255 broadcasthost
::1 localhost
::1 ip6-localhost
::1 ip6-loopback
fe80::1%lo0 localhost
ff00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts
0.0.0.0 0.0.0.0
```

this is not a bug.
