### ISSUE TITLE
Add Option to disable Updates

### ISSUE THREAD

**Issue by reveny** [backslashxx/bindhosts#23]
A option to disable updates would be nice. Not much more to say :)

**Comment by backslashxx** [comment]
@KOWX712 backend done https://github.com/backslashxx/bindhosts/commit/db281bb8ece3eb5fabe6e6a66aea5ec89a67bbd1

**Comment by KOWX712** [comment]
Ok plan to add a toggle beside module version in header.

**Comment by KOWX712** [comment]
All done, can close issue now.

**Comment by backslashxx** [comment]
> All done, can close issue now.

mind if I squash the fix onto your changes?
