### ISSUE TITLE
How do i edit

### ISSUE THREAD

**Issue by DRA7** [backslashxx/bindhosts#24]
Idk how to get that ui wheere i can change rules and modes and add configs im using magisk 28.1

**Comment by backslashxx** [comment]
> Idk how to get that ui wheere i can change rules and modes and add configs im using magisk 28.1

You can use either ksuwebui or MMRL

**Comment by DRA7** [comment]
Ty :))

**Comment by backslashxx** [comment]
you might want to try latest changes

https://github.com/backslashxx/bindhosts/actions/runs/12282397125

https://nightly.link/backslashxx/bindhosts/actions/runs/12282397125

**Comment by DRA7** [comment]
Ohh the new update opens up mmrl niceee thanks again!
