### ISSUE TITLE
error while running action.sh

### ISSUE THREAD

**Issue by ZG089** [backslashxx/bindhosts#25]
wget fails to download hostslist from given links

Logs: 

> [+] processing sources
wget: bad address 'adaway.org'
wget: bad address 'raw.githubusercontent.com'
[.]
[+] grabbing..
[>] https://adaway.org/hosts.txt
[x] failed downloading https://adaway.org/hosts.txt
[+] grabbing..
[>] https://raw.githubusercontent.com/r-a-y/mobile-hosts/master/AdguardDNS.txt
[x] failed downloading https://raw.githubusercontent.com/r-a-y/mobile-hosts/master/AdguardDNS.txt
[+] grabbing..
[>] https://hblock.molinero.dev/hosts
wget: bad address 'hblock.molinero.dev'
[x] failed downloading https://hblock.molinero.dev/hosts

**Comment by backslashxx** [comment]
Let's see if disabling "brutal busybox" works

**Comment by backslashxx** [comment]
OK to just log this properly, here was the offending module

```
id=busybox-brutal
name=Brutal Busybox
version=v1.34.0.1
versionCode=13401
author=FeraVolt
description=Brutal busybox with almost all available applets. Compiled with NDK clang + LTO + Ofast. Has all Android NDK patches. ARMv7/ARMv8, x86/x86-64.
```
