### ISSUE TITLE
Failed to block ads

### ISSUE THREAD

**Issue by ggeo-git** [backslashxx/bindhosts#26]
I'm using magisk alpha in its version 28101 and the module cannot block ads

**Comment by ggeo-git** [comment]
![Screenshot_20241213_221137](https://github.com/user-attachments/assets/610f3613-4107-415e-8ae1-ac63bfafb6db)
![Screenshot_20241213_221104_KsuWebUI](https://github.com/user-attachments/assets/e7baf0c3-53c8-46a6-9542-809e56f0ac72)
![Screenshot_20241213_221046_Chrome](https://github.com/user-attachments/assets/cccb717e-7267-485f-aaeb-af9ec8789fef)

Magisk Alpha: 47cc532d-alpha (28101)
Android: 13
Device: Samsung Galaxy A03 (A035M)

**Comment by backslashxx** [comment]
what browser are you using?

can you try adding "s.youtube.com" on blacklist, reload lists
and then opening youtube to see if blocking works?

**Comment by KOWX712** [comment]
Magisk 28101 is working on my side. Due to the browser cache, sometime the effect won't take immediately although the hosts already updated. Besides, make sure there's no other module/app is overwriting the hosts. As you're using mode 0, you can check `/system/etc/hosts` to determine if bindhosts is working.

**Comment by ggeo-git** [comment]
I checked the host files and they were modified by the module, I did an investigation on the modules I was using and came to the conclusion that it could be "hide my root v2" so I uninstalled it and bindhost started working/blocking ads perfectly again 

![Screenshot_20241214_101243_KsuWebUI](https://github.com/user-attachments/assets/d3716085-9ade-4cd7-8819-37c652c4d4e8)
![Screenshot_20241214_100640_Chrome](https://github.com/user-attachments/assets/ab7941c6-a6da-413b-b437-a9400dd65a40)

This was the module that made bindhost unusable: 
https://t.me/MeowRedirect/469
