### ISSUE TITLE
Action button in Magisk not working correctly

### ISSUE THREAD

**Issue by Whyme3** [backslashxx/bindhosts#33]
Ever since V1.7.9 I get this after I hit action in magisk:
The webpage at https://mui.kernelsu.org/index.html could not be loaded because:

net::ERR_INVALID_RESPONSE

I tried the new V1.8.0 and I still get the same problem too.

**Comment by KOWX712** [comment]
Do you have KSUWebUIStandalone or MMRL installed?

**Comment by Whyme3** [comment]
I have both installed

**Comment by backslashxx** [comment]
can you provide device info?
say android version, model, kernel
though it can also be webview?

**Comment by KOWX712** [comment]
> I have both installed

Can you access to webui in KSUWebUI or MMRL? Is it happen only when you use magisk action?

**Comment by Whyme3** [comment]
I can access it in the KSUWebUI but I just tried on the MMRL app and the action button works but for the webUI part in MMRL I get the error message again and I'm on V1.7.8

**Comment by Whyme3** [comment]
I just uninstalled MMRL and the action button is working again with the KSUWebUI so it seems the fault might lay with MMRL

**Comment by backslashxx** [comment]
> I just uninstalled MMRL and the action button is working again with the KSUWebUI so it seems the fault might lay with MMRL

is this MMRL beta?

**Comment by backslashxx** [comment]
> I just uninstalled MMRL and the action button is working again with the KSUWebUI so it seems the fault might lay with MMRL

feel free to try
https://github.com/backslashxx/bindhosts/actions/runs/12345775220
https://nightly.link/backslashxx/bindhosts/actions/runs/12345775220

**Comment by Whyme3** [comment]
I reinstalled MMRL and tried the new BindHosts nightly and it's working correctly again. Thank you.
