### ISSUE TITLE
Adblocking doesnt works

### ISSUE THREAD

**Issue by balkasserhat** [backslashxx/bindhosts#35]
İm using it in mode=0 previously tested it with susfs but it seems to be not working. İm using in poco x3 pro with infinity x rom... Hosts file seems to be not modified.
My kernel is non gki but it supports ksu and susfs

![Screenshot_20241216-121032_Chrome](https://github.com/user-attachments/assets/01197810-a7c0-4a1f-8e98-3f1fd97d7cb3)
![Screenshot_20241216-121039_Chrome](https://github.com/user-attachments/assets/b2f0f1c7-84cf-4faa-957c-549ee59e1acc)
![Screenshot_20241216-121056_KernelSU](https://github.com/user-attachments/assets/ffc892af-e4e4-4c49-8d35-8d69ce28c3e3)
![Screenshot_20241216-121223_MiXplorer](https://github.com/user-attachments/assets/d2519fa3-3075-4a0e-aefa-b845a51422a7)
![Screenshot_20241216-121111_KernelSU](https://github.com/user-attachments/assets/0fb51685-9e96-4cde-b1e6-de52118c63ba)
![Screenshot_20241216-121243_KernelSU](https://github.com/user-attachments/assets/29d79437-e71b-4cdf-85fe-8db0c62e4dec)
![Screenshot_20241216-121609_Chrome](https://github.com/user-attachments/assets/40eafbec-335d-4332-830f-61f239540d2a)
![Screenshot_20241216-121618_Ayarlar](https://github.com/user-attachments/assets/eaf792d1-fb4e-471f-bd58-d655223c462a)

**Comment by backslashxx** [comment]
whose your kernel dev?
clearly if kernel has susfs it should have been in mode 1.
your kernel dev probably disabled susfs logs so bindhosts cant probe it.

youll have to try to override
try mode 8 or mode 1

**Comment by balkasserhat** [comment]
No no i took the screenshot after i deleted the module for testing, previously it was in mode=1 but ill try again, meanwhile i tried it in mode 4 after installing the required modules and result is same, now trying mode 1 again

![Screenshot_20241216-124210_KernelSU](https://github.com/user-attachments/assets/a3df100b-c566-4b4b-8ead-af1090379f7f)
![Screenshot_20241216-124159_Chrome](https://github.com/user-attachments/assets/7d5e35eb-3fec-4163-a04a-8f8c79df164c)

**Comment by backslashxx** [comment]
@balkasserhat the easiest way to try is to add
s.youtube.com to blacklist, load lists and then open youtube app

**Comment by balkasserhat** [comment]
Mode 1 result.. im using vanced in yt probably it wouldnt make a difference, the issue is not in Chrome its in all apps and in hotspot too

![Screenshot_20241216-125031_KernelSU](https://github.com/user-attachments/assets/19956cc4-8db7-4162-9a14-af5b0ebb30d7)
![Screenshot_20241216-125054_Chrome](https://github.com/user-attachments/assets/cd1b7fc3-d28f-4d8f-92eb-0d215d73ed9f)
![Screenshot_20241216-125500_KernelSU](https://github.com/user-attachments/assets/ab371f85-d237-4ba5-948c-eff15cbf17cf)

**Comment by backslashxx** [comment]
huh this is plain weird, how about mode 8?

**Comment by balkasserhat** [comment]
Mode 8 is the same theres a problem for sure but seems to be not about the module, premade hosts modules also fails to block ads ive no idea why
I dont think changing ttl has to do with it i was able to use it before.. i will check if the problem is with Kernel or with rom thanks for helping out


![Screenshot_20241216-131705_Chrome](https://github.com/user-attachments/assets/afd63f98-1a75-4f62-ab7c-b1adc2ad35ff)

![Screenshot_20241216-131615_KernelSU](https://github.com/user-attachments/assets/cd420585-a3d8-47e3-9b49-257b71c4d444)

**Comment by balkasserhat** [comment]
Thank you for both this ans nongki ksu manager support ❤️

**Comment by backslashxx** [comment]
> Mode=1 with adaway with custom adaway root settings selected in ksu manager seems to be working not sure why

good thing I kept adaway compatibility hey!
