### ISSUE TITLE
Support network acceleration by changing the host

### ISSUE THREAD

**Issue by wentywenty** [backslashxx/bindhosts#38]
Some regions restrict the network of websites such as github.com. By changing the host of websites such as github and steam, the network can be accelerated, just like https://github.com/BeyondDimension/SteamTools and https://github.com/maxiaof/github-hosts. Can this module also achieve this function? I am sorry for mentioning other projects. Thanks to the author for developing the module.

**Comment by backslashxx** [comment]
I am not familiar with what you are saying.
If this is like the trustpositif issue in indonesia
you can try adding 
```https://raw.githubusercontent.com/maxiaof/github-hosts/refs/heads/master/hosts```
to custom sources.

ofcourse you have to add
```
185.199.108.133 raw.githubusercontent.com
```
to custom rules first

**Comment by KOWX712** [comment]
Since it is not an issue yet, you can try and tell, by adding your custom host content to `/data/adb/bindhosts/custom.txt` and run `action.sh`. Not all domains can bypass regional restrictions using hosts, some may vary by region.
