### ISSUE TITLE
Feature Request: DNS capture

### ISSUE THREAD

**Issue by dynux90** [backslashxx/bindhosts#40]
Hi, 

Like in adaway, it would be great if we can capture the DNS requests made by an App (or whole system DNS requests) and be able to block or allow them.

Feel free to ask more info.
Thanks

**Comment by backslashxx** [comment]
> Hi,
> 
> Like in adaway, it would be great if we can capture the DNS requests made by an App (or whole system DNS requests) and be able to block or allow them.
> 
> Feel free to ask more info. Thanks

this is available but this will rely if your system has tcpdump
open termux

```su
bindhosts --tcpdump
```

I guess I have not documented it yet, maybe someday I will make a usage documentation!

**Comment by backslashxx** [comment]
https://github.com/backslashxx/bindhosts/blob/master/Documentation/usage.md
